"""add vendor settlement module

Revision ID: 1bb76572422b
Revises: 59a6bdc55556
Create Date: 2026-05-07 23:09:09.488479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb76572422b'
down_revision = '59a6bdc55556'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_settlement',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('settlement_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('settlement_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_vendor_settlement_invoice_id_invoice'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_vendor_settlement_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_vendor_settlement_payment_id_payment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_vendor_settlement_vendor_id_vendor'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_settlement')),
    sa.UniqueConstraint('organization_id', 'settlement_reference', name='uq_vendor_settlement_reference_per_org')
    )
    op.create_index(op.f('ix_vendor_settlement_invoice_id'), 'vendor_settlement', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_vendor_settlement_organization_id'), 'vendor_settlement', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vendor_settlement_payment_id'), 'vendor_settlement', ['payment_id'], unique=False)
    op.create_index(op.f('ix_vendor_settlement_settlement_reference'), 'vendor_settlement', ['settlement_reference'], unique=False)
    op.create_index(op.f('ix_vendor_settlement_vendor_id'), 'vendor_settlement', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_settlement_vendor_id'), table_name='vendor_settlement')
    op.drop_index(op.f('ix_vendor_settlement_settlement_reference'), table_name='vendor_settlement')
    op.drop_index(op.f('ix_vendor_settlement_payment_id'), table_name='vendor_settlement')
    op.drop_index(op.f('ix_vendor_settlement_organization_id'), table_name='vendor_settlement')
    op.drop_index(op.f('ix_vendor_settlement_invoice_id'), table_name='vendor_settlement')
    op.drop_table('vendor_settlement')
    # ### end Alembic commands ###
