"""add_idp_models

Revision ID: 3b784b0b57a0
Revises: e2d4f6a8b0c1
Create Date: 2026-05-09 17:23:56.760981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b784b0b57a0'
down_revision = 'e2d4f6a8b0c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('linked_entity_type', sa.String(length=50), nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('human_review_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_document_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], name=op.f('fk_document_uploaded_by_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_organization_id'), 'document', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_uploaded_by_user_id'), 'document', ['uploaded_by_user_id'], unique=False)
    op.create_table('document_version',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_version_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_document_version_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], name=op.f('fk_document_version_uploaded_by_user_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_version'))
    )
    op.create_index(op.f('ix_document_version_document_id'), 'document_version', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_version_organization_id'), 'document_version', ['organization_id'], unique=False)
    op.create_table('document_extraction',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('extraction_engine', sa.String(length=100), nullable=False),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_extraction_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], name=op.f('fk_document_extraction_document_version_id_document_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_document_extraction_organization_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_extraction'))
    )
    op.create_index(op.f('ix_document_extraction_document_id'), 'document_extraction', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_extraction_organization_id'), 'document_extraction', ['organization_id'], unique=False)
    op.alter_column('alert', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('audit_log', sa.Column('field_name', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('audit_log', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('audit_log', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.add_column('audit_log', sa.Column('actor_role', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_log', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_log', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.create_index('ix_audit_log_actor_lookup', 'audit_log', ['organization_id', 'actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_log_entity_lookup', 'audit_log', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_tenant_time', 'audit_log', ['organization_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('fk_audit_log_user_id_user'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_log_actor_user_id_user'), 'audit_log', 'user', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_log', 'ip_address')
    op.drop_column('audit_log', 'old_values')
    op.drop_column('audit_log', 'user_agent')
    op.drop_column('audit_log', 'user_id')
    op.drop_column('audit_log', 'new_values')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_audit_log_actor_user_id_user'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_log_user_id_user'), 'audit_log', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_audit_log_tenant_time', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_lookup', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_actor_lookup', table_name='audit_log')
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.alter_column('audit_log', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_log', 'metadata_json')
    op.drop_column('audit_log', 'reason')
    op.drop_column('audit_log', 'actor_role')
    op.drop_column('audit_log', 'actor_user_id')
    op.drop_column('audit_log', 'new_value')
    op.drop_column('audit_log', 'old_value')
    op.drop_column('audit_log', 'field_name')
    op.alter_column('alert', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_document_extraction_organization_id'), table_name='document_extraction')
    op.drop_index(op.f('ix_document_extraction_document_id'), table_name='document_extraction')
    op.drop_table('document_extraction')
    op.drop_index(op.f('ix_document_version_organization_id'), table_name='document_version')
    op.drop_index(op.f('ix_document_version_document_id'), table_name='document_version')
    op.drop_table('document_version')
    op.drop_index(op.f('ix_document_uploaded_by_user_id'), table_name='document')
    op.drop_index(op.f('ix_document_organization_id'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
