"""Add due_date to Invoice

Revision ID: 5a82a9dbcef4
Revises: 1bb76572422b
Create Date: 2026-05-08 11:03:50.407243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a82a9dbcef4'
down_revision = '1bb76572422b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_invoice_due_date'), 'invoice', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_due_date'), table_name='invoice')
    op.drop_column('invoice', 'due_date')
    # ### end Alembic commands ###
