"""add_grn_models

Revision ID: a21944a8ccd5
Revises: e1f50f1acfa5
Create Date: 2026-05-11 11:32:51.835060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21944a8ccd5'
down_revision = 'e1f50f1acfa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grn',
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('grn_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_by', sa.String(length=255), nullable=False),
    sa.Column('warehouse_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_received_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_grn_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], name=op.f('fk_grn_po_id_purchase_order'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grn')),
    sa.UniqueConstraint('organization_id', 'grn_number', name='uq_grn_organization_id_grn_number')
    )
    op.create_index(op.f('ix_grn_grn_number'), 'grn', ['grn_number'], unique=False)
    op.create_index(op.f('ix_grn_organization_id'), 'grn', ['organization_id'], unique=False)
    op.create_index(op.f('ix_grn_po_id'), 'grn', ['po_id'], unique=False)
    op.create_table('grn_line_item',
    sa.Column('grn_id', sa.UUID(), nullable=False),
    sa.Column('po_line_item_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_damaged', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_pending', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['grn.id'], name=op.f('fk_grn_line_item_grn_id_grn'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_grn_line_item_organization_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_line_item_id'], ['p_o_line_item.id'], name=op.f('fk_grn_line_item_po_line_item_id_p_o_line_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grn_line_item'))
    )
    op.create_index(op.f('ix_grn_line_item_grn_id'), 'grn_line_item', ['grn_id'], unique=False)
    op.create_index(op.f('ix_grn_line_item_organization_id'), 'grn_line_item', ['organization_id'], unique=False)
    op.create_index(op.f('ix_grn_line_item_po_line_item_id'), 'grn_line_item', ['po_line_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grn_line_item_po_line_item_id'), table_name='grn_line_item')
    op.drop_index(op.f('ix_grn_line_item_organization_id'), table_name='grn_line_item')
    op.drop_index(op.f('ix_grn_line_item_grn_id'), table_name='grn_line_item')
    op.drop_table('grn_line_item')
    op.drop_index(op.f('ix_grn_po_id'), table_name='grn')
    op.drop_index(op.f('ix_grn_organization_id'), table_name='grn')
    op.drop_index(op.f('ix_grn_grn_number'), table_name='grn')
    op.drop_table('grn')
    # ### end Alembic commands ###
