"""add_operational_error_table

Revision ID: e1f50f1acfa5
Revises: 3b784b0b57a0
Create Date: 2026-05-09 21:11:11.636721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f50f1acfa5'
down_revision = '3b784b0b57a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_errors'))
    )
    op.create_index(op.f('ix_operational_errors_error_type'), 'operational_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_operational_errors_request_id'), 'operational_errors', ['request_id'], unique=False)
    op.create_index(op.f('ix_operational_errors_service'), 'operational_errors', ['service'], unique=False)
    op.create_index(op.f('ix_operational_errors_tenant_id'), 'operational_errors', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operational_errors_tenant_id'), table_name='operational_errors')
    op.drop_index(op.f('ix_operational_errors_service'), table_name='operational_errors')
    op.drop_index(op.f('ix_operational_errors_request_id'), table_name='operational_errors')
    op.drop_index(op.f('ix_operational_errors_error_type'), table_name='operational_errors')
    op.drop_table('operational_errors')
    # ### end Alembic commands ###
